### ISSUE TITLE
mid360 configs

### ISSUE THREAD

**Issue by ubicray** [koide3/glim#43]
Hi!
First of all, great project!

I'm interested in testing it out with a livox mid460 and an Orin NX
I see that you have used mid360 for some outdoor settings...
What were the configuration values you used?

**Comment by koide3** [comment]
I used almost the same parameter set as the default one. The required changes are as follows:

- config_ros.json
  - Set `glim_ros/acc_scale` to `9.80665`
  - Change `(imu|points)_topic`
- config_sensors.json
  - Change `sensors/T_lidar_imu`

**Comment by koide3** [comment]
I created a wiki page for sensor setup https://github.com/koide3/glim/wiki/Sensor-setup-guide .

**Comment by Gabryss** [comment]
Hi !
Could you explain me how did you figure out the Transform between the lidar and the imu on the mid360 ? I am looking for it and haven't been able to find it in the doc.
Thank you very much.

**Comment by oliver-batchelor** [comment]
> Hi ! Could you explain me how did you figure out the Transform between the lidar and the imu on the mid360 ? I am looking for it and haven't been able to find it in the doc. Thank you very much.

It is listed in a few places, I am not sure how to confirm if this is accurate. But for example there is this...

https://github.com/Livox-SDK/LIO-Livox/blob/2296e4bea59bcfec09624a6f052fd6bfbe2b1e6a/launch/mid360.launch#L17C1-L20C97

**Comment by JoLichtenfeld** [comment]
I have a followup question on this: 
The default livox_ros_driver2 publishes PointCloud and IMU in the same frame. This causes GLIM to throw lots of errors
`TF_SELF_TRANSFORM: Ignoring transform ... with frame_id and  child_frame_id ... because they are the same`

How do you guys handle this? Do you remap the imu topic with a different frame_id?
The japanese setup guide at https://github.com/koide3/glim/wiki/Sensor-setup-guide does not mention this.

**Comment by JoLichtenfeld** [comment]
Sorry, my bad. This only happens if `"publish_imu2lidar": true` in config_ros.json.
Still I don't understand why Livox specifies the same frame for both...
